<?php /** @var array $clase_extra */ /** @var array $errors */ /** @var array $deportistas */ /** @var array $coaches */ /** @var array $competencias */ /** @var array $eventos_federados */ /** @var array $selected_deportistas */ ?>
<section class="page">
    <div class="page-header"><div><h1>Nueva clase extra</h1><p>Selecciona las deportistas que prepararán juntas la competencia. La pista se prorratea automáticamente.</p></div><a class="button ghost" href="<?= e(base_url('/?page=clases')) ?>">Volver</a></div>
    <?php if (!empty($errors)): ?><div class="alert danger"><?php foreach ($errors as $error): ?><p><?= e($error) ?></p><?php endforeach; ?></div><?php endif; ?>
    <form class="form" method="post" action="<?= e(base_url('/?page=clases&action=extra-create')) ?>">
        <label>Evento federado<select name="evento_federado_id" required onchange="this.form.submit()"><option value="0">Selecciona evento</option><?php foreach ($eventos_federados as $evento): ?><option value="<?= e((string) $evento['id']) ?>" <?= (int)$clase_extra['evento_federado_id']===(int)$evento['id']?'selected':'' ?>><?= e($evento['nombre'].' · '.$evento['nivel'].' · '.$evento['fecha_inicio']) ?></option><?php endforeach; ?></select></label>
        <div class="form-row"><label>Coach<select name="coach_id" required><option value="">Selecciona un coach</option><?php foreach ($coaches as $coach): ?><option value="<?= e((string)$coach['id']) ?>" <?= (int)$clase_extra['coach_id']===(int)$coach['id']?'selected':'' ?>><?= e($coach['nombre']) ?></option><?php endforeach; ?></select></label><label>Fecha<input type="date" name="fecha" required value="<?= e($clase_extra['fecha']) ?>"></label></div>
        <div class="form-row"><label>Duración (minutos)<input type="number" min="0" name="duracion_min" value="<?= e((string)$clase_extra['duracion_min']) ?>"></label><label>Valor fijo por clase<input type="number" value="10000" readonly><input type="hidden" name="valor_clase" value="10000"><small class="muted">Valor fijo para clases extras.</small></label><label>Costo total pista<input type="number" step="0.01" min="0" name="costo_pista" required value="<?= e((string)$clase_extra['costo_pista']) ?>"></label></div>
        <fieldset><legend>Inscritas en el evento (<?= e((string) count($deportistas)) ?>)</legend><?php if (empty($deportistas)): ?><p class="muted">Selecciona un evento federado con inscritas.</p><?php endif; ?><?php foreach ($deportistas as $deportista): ?><label><input type="checkbox" name="deportistas[]" value="<?= e((string)$deportista['id']) ?>" <?= in_array((int)$deportista['id'], $selected_deportistas, true)?'checked':'' ?>> <?= e($deportista['nombre']) ?> <span class="muted">(<?= e($deportista['nivel']) ?>)</span></label><?php endforeach; ?></fieldset>
        <label>Estado<select name="estado"><?php foreach (['programada','realizada','anulada'] as $estado): ?><option value="<?= e($estado) ?>" <?= $clase_extra['estado']===$estado?'selected':'' ?>><?= e(ucfirst($estado)) ?></option><?php endforeach; ?></select></label>
        <label>Notas<input type="text" name="notas" value="<?= e($clase_extra['notas']) ?>"></label>
        <div class="form-actions"><button type="submit" class="button">Crear clase extra</button><a class="button ghost" href="<?= e(base_url('/?page=clases')) ?>">Cancelar</a></div>
    </form>
</section>
